version: '2'
services:
    firefox:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
    firefox:
        build: .
        ports:
            - "5001:5000"
        volumes:
            - .:/app
            